import type { SignTemplate } from "./types";

export const HEADLINE_OPTIONS = [
  "DONATE",
  "DONATE TODAY",
  "HELP A NEIGHBOR",
  "GIVE BACK",
  "COMMUNITY DONATION",
];

export const EMPHASIS_OPTIONS = [
  "ESSENTIALS",
  "FOOD",
  "CLOTHES",
  "SCHOOL SUPPLIES",
  "BABY ITEMS",
  "PET SUPPLIES",
  "WINTER COATS",
  "HYGIENE",
  "BOOKS",
  "TOYS",
];

export const SUBTITLE_OPTIONS = [
  "To Those Most In Need",
  "Support Families Nearby",
  "Help Local Children",
  "Support Our Community",
  "Every Donation Matters",
];

export const SLOGAN_OPTIONS = [
  "Together We Can Change Lives",
  "Helping Our Community",
  "Small Acts. Big Impact.",
  "Neighbors Helping Neighbors.",
  "One Community. Endless Impact.",
];

export const templates: SignTemplate[] = [
  {
    id: "minimal",
    name: "Minimal",
    category: "Style",
    description: "Clean type, generous space, quiet confidence.",
    layout: "centered",
    defaults: {
      themeId: "clean-white",
      headline: "DONATE",
      emphasis: "ESSENTIALS",
      subtitle: "To Those Most In Need",
      slogan: "Neighbors Helping Neighbors.",
      iconId: "heart",
      mapStyle: "none",
    },
  },
  {
    id: "community",
    name: "Community",
    category: "Style",
    description: "Warm and welcoming — made for neighborhoods.",
    layout: "warm",
    defaults: {
      themeId: "hope-green",
      headline: "HELP A NEIGHBOR",
      emphasis: "ESSENTIALS",
      subtitle: "Support Families Nearby",
      slogan: "One Community. Endless Impact.",
      iconId: "handshake",
      mapStyle: "city",
    },
  },
  {
    id: "modern",
    name: "Modern",
    category: "Style",
    description: "Bold emphasis with contemporary structure.",
    layout: "split",
    defaults: {
      themeId: "deep-navy",
      headline: "GIVE BACK",
      emphasis: "FOOD",
      subtitle: "Support Our Community",
      slogan: "Small Acts. Big Impact.",
      iconId: "leaf",
      mapStyle: "none",
    },
  },
  {
    id: "church",
    name: "Church",
    category: "Organization",
    description: "Gentle reverence for faith community drives.",
    layout: "banner",
    defaults: {
      themeId: "warm-gray",
      headline: "DONATE TODAY",
      emphasis: "ESSENTIALS",
      subtitle: "Every Donation Matters",
      slogan: "Together We Can Change Lives",
      iconId: "church",
      mapStyle: "none",
    },
  },
  {
    id: "school",
    name: "School",
    category: "Organization",
    description: "Bright and clear for campus collection points.",
    layout: "poster",
    defaults: {
      themeId: "community-blue",
      headline: "GIVE BACK",
      emphasis: "SCHOOL SUPPLIES",
      subtitle: "Help Local Children",
      slogan: "Helping Our Community",
      iconId: "school",
      mapStyle: "none",
    },
  },
  {
    id: "holiday",
    name: "Holiday",
    category: "Seasonal",
    description: "Festive warmth without clutter or commercial noise.",
    layout: "warm",
    defaults: {
      themeId: "sunrise-orange",
      headline: "DONATE",
      emphasis: "TOYS",
      subtitle: "Support Families Nearby",
      slogan: "Together We Can Change Lives",
      iconId: "heart",
      mapStyle: "none",
    },
  },
  {
    id: "food-drive",
    name: "Food Drive",
    category: "Cause",
    description: "Nourishing, abundant, easy to read from the street.",
    layout: "poster",
    defaults: {
      themeId: "hope-green",
      headline: "DONATE TODAY",
      emphasis: "FOOD",
      subtitle: "To Those Most In Need",
      slogan: "Neighbors Helping Neighbors.",
      iconId: "food",
      mapStyle: "city",
    },
  },
  {
    id: "winter-essentials",
    name: "Winter Essentials",
    category: "Cause",
    description: "Cozy urgency — coats, blankets, warmth.",
    layout: "banner",
    defaults: {
      themeId: "deep-navy",
      headline: "HELP A NEIGHBOR",
      emphasis: "WINTER COATS",
      subtitle: "Support Families Nearby",
      slogan: "Small Acts. Big Impact.",
      iconId: "home",
      mapStyle: "none",
    },
  },
  {
    id: "back-to-school",
    name: "Back To School",
    category: "Cause",
    description: "Optimistic start-of-year energy for supply drives.",
    layout: "split",
    defaults: {
      themeId: "community-blue",
      headline: "DONATE",
      emphasis: "SCHOOL SUPPLIES",
      subtitle: "Help Local Children",
      slogan: "Helping Our Community",
      iconId: "backpack",
      mapStyle: "none",
    },
  },
  {
    id: "baby-supplies",
    name: "Baby Supplies",
    category: "Cause",
    description: "Soft, nurturing palette for infant essentials.",
    layout: "warm",
    defaults: {
      themeId: "warm-gray",
      headline: "GIVE BACK",
      emphasis: "BABY ITEMS",
      subtitle: "Support Families Nearby",
      slogan: "One Community. Endless Impact.",
      iconId: "baby",
      mapStyle: "none",
    },
  },
  {
    id: "pet-supplies",
    name: "Pet Supplies",
    category: "Cause",
    description: "Friendly and playful for animal welfare drives.",
    layout: "centered",
    defaults: {
      themeId: "sunrise-orange",
      headline: "DONATE",
      emphasis: "PET SUPPLIES",
      subtitle: "Every Donation Matters",
      slogan: "Neighbors Helping Neighbors.",
      iconId: "pet",
      mapStyle: "none",
    },
  },
  {
    id: "disaster-relief",
    name: "Disaster Relief",
    category: "Cause",
    description: "Clear and calm when communities need fast help.",
    layout: "poster",
    defaults: {
      themeId: "charcoal",
      headline: "HELP A NEIGHBOR",
      emphasis: "ESSENTIALS",
      subtitle: "To Those Most In Need",
      slogan: "Together We Can Change Lives",
      iconId: "home",
      mapStyle: "state",
    },
  },
  {
    id: "general-essentials",
    name: "General Essentials",
    category: "Cause",
    description: "The versatile default for ongoing collection.",
    layout: "centered",
    defaults: {
      themeId: "hope-green",
      headline: "COMMUNITY DONATION",
      emphasis: "ESSENTIALS",
      subtitle: "Support Our Community",
      slogan: "One Community. Endless Impact.",
      iconId: "family",
      mapStyle: "skyline",
    },
  },
];

export function getTemplate(id: string) {
  return templates.find((t) => t.id === id) ?? templates[0];
}
