import type { ColorTheme, ThemeId } from "./types";

export const themes: ColorTheme[] = [
  {
    id: "hope-green",
    name: "Hope Green",
    description: "Soft meadow green — calm, generous, alive.",
    background: "#E8F3EA",
    surface: "#F7FBF7",
    primary: "#2F6B4F",
    primaryText: "#FFFFFF",
    accent: "#5FA37A",
    muted: "#4A6354",
    text: "#1C3228",
    soft: "#D5E8D9",
    border: "#B7D0BD",
  },
  {
    id: "sunrise-orange",
    name: "Sunrise Orange",
    description: "Warm dawn light — welcoming and energetic.",
    background: "#FFF1E6",
    surface: "#FFF8F2",
    primary: "#C45C26",
    primaryText: "#FFFFFF",
    accent: "#E08A4F",
    muted: "#6E4A35",
    text: "#2C1A12",
    soft: "#F6DCC7",
    border: "#E8C3A5",
  },
  {
    id: "deep-navy",
    name: "Deep Navy",
    description: "Trusted and steady — civic confidence.",
    background: "#E7EEF6",
    surface: "#F5F8FC",
    primary: "#1E3A5F",
    primaryText: "#FFFFFF",
    accent: "#3D6FA3",
    muted: "#44566B",
    text: "#122033",
    soft: "#D5E0EC",
    border: "#B4C5D8",
  },
  {
    id: "charcoal",
    name: "Charcoal",
    description: "Quiet strength with high readability.",
    background: "#ECECEC",
    surface: "#F7F7F7",
    primary: "#2B2B2B",
    primaryText: "#FFFFFF",
    accent: "#5C5C5C",
    muted: "#555555",
    text: "#141414",
    soft: "#DDDDDD",
    border: "#C4C4C4",
  },
  {
    id: "clean-white",
    name: "Clean White",
    description: "Airy and minimal — content leads.",
    background: "#FFFFFF",
    surface: "#FFFFFF",
    primary: "#1F5C45",
    primaryText: "#FFFFFF",
    accent: "#3D8B6A",
    muted: "#5A6B63",
    text: "#1A1F1C",
    soft: "#F0F4F1",
    border: "#D7E0DA",
  },
  {
    id: "warm-gray",
    name: "Warm Gray",
    description: "Soft stone tones — neighborly and grounded.",
    background: "#F0EBE4",
    surface: "#F8F5F1",
    primary: "#5C5348",
    primaryText: "#FFFFFF",
    accent: "#8A7B6A",
    muted: "#6B6258",
    text: "#2A251F",
    soft: "#E4DDD4",
    border: "#CFC5B8",
  },
  {
    id: "community-blue",
    name: "Community Blue",
    description: "Open sky blue — togetherness and clarity.",
    background: "#E6F2FB",
    surface: "#F4FAFE",
    primary: "#2A6F97",
    primaryText: "#FFFFFF",
    accent: "#4E97BE",
    muted: "#456578",
    text: "#143246",
    soft: "#D3E7F4",
    border: "#B0CBDD",
  },
];

/** Colorblind-safe overrides keep luminance structure while shifting hues. */
export const colorblindSafeOverrides: Partial<Record<ThemeId, Partial<ColorTheme>>> = {
  "hope-green": { primary: "#0072B2", accent: "#009E73", background: "#E8F1F8" },
  "sunrise-orange": { primary: "#D55E00", accent: "#E69F00", background: "#FFF4E8" },
  "community-blue": { primary: "#0072B2", accent: "#56B4E9", background: "#EAF4FB" },
};

export function getTheme(id: ThemeId, colorblindSafe = false): ColorTheme {
  const base = themes.find((t) => t.id === id) ?? themes[0];
  if (!colorblindSafe) return base;
  return { ...base, ...(colorblindSafeOverrides[id] ?? {}) };
}
